# Generated by Django 4.1.1 on 2022-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_album_albumlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='albumlist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='songlist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='collection',
            name='albumlist',
            field=models.ManyToManyField(to='playlist.album'),
        ),
        migrations.AddField(
            model_name='collection',
            name='songlist',
            field=models.ManyToManyField(to='playlist.song'),
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
