# Generated by Django 4.1.1 on 2022-10-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_transaction_remove_album_albumlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
